### PR TITLE
Allow fix_updatedb to be used on Suse-11

### PR DESCRIPTION
**Pull request by Phil-Friderici**
Local team is starting to use the module in production more & more \o/

They investigated in the updatedb functionality on Suse-11 and requested that the module should take care for Suse-11 as well.

Additionally I have updated the error messages to be aligned with the supported OSfamilies again. Did forget that the last time :\

have phun & a nice weekend

### CODE REVIEW

**Comment by kylefu8** [comment]
Thanks for your PR.
Seems Travis CI reports error this time.
I will check this later:)

**Comment by Phil-Friderici** [comment]
Rake was updated recently and the newest version does need Ruby 1.8.7.
My last commit does pin Ruby 1.8.7 to use rake v10 only.

**Comment by kylefu8** [comment]
Thanks again!

**Comment by Phil-Friderici** [comment]
Thanks @kylefu8 for reviewing, merging and creating a new release :)

**Pull request merged**
