### PR TITLE
Refactor spec tests

### PR DESCRIPTION
**Pull request by Phil-Friderici**

### CODE REVIEW

**Comment by Phil-Friderici** [comment]
Removes a typo and the last fragments from Array switch.
Sorry for being quite pedantic sometimes.

**Comment by Phil-Friderici** [comment]
@kylefu8: I have refactored the spec tests and now they run need half the time to run :)
If you have any questions, don't hesitate to ask!

Please add a release tag, to do so:
<pre>
git checkout master
git pull
git tag -a 'v0.0.1' -m 'v0.0.1'
git push --tags
</pre>

I guess that there will be some discussions for the list of services to be managed by default for the fix_services_services functionality.

Additional I think we can now start to refactor the exec resources using ```sed``` into ```file_line()``` [1]


[1] https://github.com/puppetlabs/puppetlabs-stdlib#file_line

**Comment by kylefu8** [comment]
Thank you, my puppet guru:)

**Comment by Phil-Friderici** [comment]
@kylefu8 thanks for reviewing and merging :)

**Pull request merged**
