### PR TITLE
adding tweak for Pulseaudio spawning

### PR DESCRIPTION
**Pull request by Phil-Friderici**
@kylefu8 Hope life is good to you :)

This patch adds functionality to disable PulseAudio from spawning.
If you don't have time to continue maintaining this module, I can take over the ownership. Please let me know.

### CODE REVIEW

**Comment by Phil-Friderici** [comment]
Thanks @kylefu8 !

**Comment by Phil-Friderici** [comment]
Sorry for the spam, could you create a new release version/tag ?
And as said before, just do the work if you want to.

**Comment by kylefu8** [comment]
@Phil-Friderici Sorry for the late reply..
I'm learning and working on new stuff(mainly Azure and network) these days.
Everything is fine:) How are you there?
And I'm afraid I don't have much time to look into puppet. So that would be good if you can take over this module.
Thank you very much!

**Comment by Phil-Friderici** [comment]
No worries, there are no responsibilites on your side ;)
Glad to see that you are having phun on your new work place.

Life is mostly good to me, just missing Juliana who also left us now.
For the rest the same default values are still valid.

Ok, I'll take over the module maintenance and fork it to my namespace.

Thanks again for the good time I had with you creating it. Still smiling bright when I think back to it :)

**Comment by kylefu8** [comment]
Thank you for your support in a long time. It's my honor with working with the great man like you and Juliana. I will always remember you guys! Let's keep in touch:)

**Comment by Phil-Friderici** [comment]
The pleasure was on my side. If you ever have a Puppet related question, use our connection on Linkedin :)

**Pull request merged**
